// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApRDU2m_UvhsmKqLKKFxZaAwno_EV9WPA',
    appId: '1:1094126769484:web:c819bab387bbc78b5aabe9',
    messagingSenderId: '1094126769484',
    projectId: 'giftoyou-ad070',
    authDomain: 'giftoyou-ad070.firebaseapp.com',
    storageBucket: 'giftoyou-ad070.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLJHejjK8gZaq5VAufqIft7KEsVTD3SaY',
    appId: '1:1094126769484:android:1698f02964f936d65aabe9',
    messagingSenderId: '1094126769484',
    projectId: 'giftoyou-ad070',
    storageBucket: 'giftoyou-ad070.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo6J0qcEr4bQovhlB0XsPqQMPX1Dq1Z8Y',
    appId: '1:1094126769484:ios:5e4a6c3360e97e6e5aabe9',
    messagingSenderId: '1094126769484',
    projectId: 'giftoyou-ad070',
    storageBucket: 'giftoyou-ad070.firebasestorage.app',
    iosBundleId: 'com.example.giftoyou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo6J0qcEr4bQovhlB0XsPqQMPX1Dq1Z8Y',
    appId: '1:1094126769484:ios:5e4a6c3360e97e6e5aabe9',
    messagingSenderId: '1094126769484',
    projectId: 'giftoyou-ad070',
    storageBucket: 'giftoyou-ad070.firebasestorage.app',
    iosBundleId: 'com.example.giftoyou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApRDU2m_UvhsmKqLKKFxZaAwno_EV9WPA',
    appId: '1:1094126769484:web:b57b776c327486015aabe9',
    messagingSenderId: '1094126769484',
    projectId: 'giftoyou-ad070',
    authDomain: 'giftoyou-ad070.firebaseapp.com',
    storageBucket: 'giftoyou-ad070.firebasestorage.app',
  );
}
